name: test
on:
  pull_request:
    branches:
      - testing

jobs:
  test-this-action:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: kaizencc/version-comment-bot@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}