name: test
on:
  pull_request:
    branches:
      - testing
  workflow_dispatch: {}

jobs:
  test-this-action:
    # if: contains(github.event.pull_request.title, 'chore(release):')
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment
        uses: kaizencc/version-comment-bot@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
